# Generated by Django 3.2.6 on 2021-09-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', help_text='CPF', max_length=12),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='', help_text='E-mail', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(help_text='Nome', max_length=100),
        ),
    ]
